# Generated by Django 4.1.7 on 2023-04-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_extendeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='dateJoined',
        ),
    ]
